// This file will be generated by Supabase CLI
// For now, we'll use a basic interface
export interface Database {
  public: {
    Tables: {
      [key: string]: {
        Row: any
        Insert: any
        Update: any
      }
    }
  }
}
