/** @type {import('tailwindcss').Config} */
const { lightColors, darkColors } = require('./src/design-system/tokens/colors');

module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './.storybook/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light theme colors (default)
        primary: {
          DEFAULT: lightColors.primary,
          foreground: lightColors.primaryForeground,
          subtle: lightColors.primarySubtle,
          hover: lightColors.primaryHover,
        },
        secondary: {
          DEFAULT: lightColors.secondary,
          foreground: lightColors.secondaryForeground,
          subtle: lightColors.secondarySubtle,
          hover: lightColors.secondaryHover,
        },
        success: {
          DEFAULT: lightColors.success,
          foreground: lightColors.successForeground,
          subtle: lightColors.successSubtle,
          hover: lightColors.successHover,
        },
        warning: {
          DEFAULT: lightColors.warning,
          foreground: lightColors.warningForeground,
          subtle: lightColors.warningSubtle,
          hover: lightColors.warningHover,
        },
        destructive: {
          DEFAULT: lightColors.destructive,
          foreground: lightColors.destructiveForeground,
          subtle: lightColors.destructiveSubtle,
          hover: lightColors.destructiveHover,
        },
        background: {
          DEFAULT: lightColors.background,
          subtle: lightColors.backgroundSubtle,
          element: lightColors.backgroundElement,
        },
        foreground: {
          DEFAULT: lightColors.foreground,
          subtle: lightColors.foregroundSubtle,
          muted: lightColors.foregroundMuted,
        },
        muted: {
          DEFAULT: lightColors.muted,
          foreground: lightColors.mutedForeground,
        },
        accent: {
          DEFAULT: lightColors.accent,
          foreground: lightColors.accentForeground,
        },
        border: {
          DEFAULT: lightColors.border,
          subtle: lightColors.borderSubtle,
          strong: lightColors.borderStrong,
        },
        input: lightColors.input,
        ring: lightColors.ring,
      },
      spacing: {
        // Consistent spacing scale
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '28': '112px',
        '32': '128px',
        '36': '144px',
        '40': '160px',
        '44': '176px',
        '48': '192px',
        '52': '208px',
        '56': '224px',
        '60': '240px',
        '64': '256px',
        '72': '288px',
        '80': '320px',
        '96': '384px',
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        DEFAULT: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        full: '9999px',
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '36px' }],
        '4xl': ['36px', { lineHeight: '40px' }],
        '5xl': ['48px', { lineHeight: '48px' }],
        '6xl': ['60px', { lineHeight: '60px' }],
        '7xl': ['72px', { lineHeight: '72px' }],
      },
      fontFamily: {
        sans: ['System', 'sans-serif'],
        mono: ['Courier', 'monospace'],
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
